# Generated by Django 5.0.4 on 2024-04-07 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='image_url',
        ),
    ]
