# Generated by Django 5.0.4 on 2024-04-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
