# Generated by Django 5.0.4 on 2024-04-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0002_rename_updated_carousel_updated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carousel',
            table='carousel',
        ),
    ]
