# Generated by Django 5.0.4 on 2024-04-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0004_alter_carousel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carousel',
            table='carousel',
        ),
    ]
