# Generated by Django 5.0.4 on 2024-04-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0007_alter_carousel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
