# Generated by Django 5.0.4 on 2024-04-07 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specs', models.TextField()),
                ('likes', models.PositiveIntegerField()),
                ('images_url', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specs', models.TextField()),
                ('likes', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=255)),
                ('images_url', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inventory/kit/images')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.kit')),
            ],
        ),
        migrations.AddField(
            model_name='kit',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='kits', to='inventory.product'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inventory/product/images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.product')),
            ],
        ),
    ]
